### ISSUE TITLE
Doesn't work on Adafruit QT-PY C3 and DFRobot beedtle C3 boards

### ISSUE THREAD

**Issue by Mosher23** [TheDigital1/ESP32_BTHome#3]
Hello,

I have tried using this example on both above mentioned boards. 
After compiling and successful upload nothing happens. I cannot see boards in Bluetooth environment.

Could you please assist?

Thank you

**Comment by TheDigital1** [comment]
Hi,

When you say you cannot see it in the environment... Can you explain more? You do not see it in home assistant? Or you do not see it from a phone? Using a tool like nrf connect on you phone can be helpful to see if your device is broadcasting and what data it's broadcasting.

**Comment by Mosher23** [comment]
So after I have flashed the example. I cannot see it in BTHome, Home Assistant, LightBlue. 
I tried reseting and reflashing. Same story.

**Comment by TheDigital1** [comment]
Hmm strange, you could try increasing the delay in the setup faction or removing the enter to sleep command just for test, this way it will advertise for longer. Giving an increased chance of seeing it. Another thing to try is just the example BLE advertisement code on your board to see if that is able to be seen.

**Comment by Mosher23** [comment]
Hi,
sorry for a late reply. 
Everything is working fine on Adafruit QT-Py C3.
Thank you
